# Generated by Django 3.1.2 on 2020-10-04 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MassageDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('hour', models.TimeField()),
                ('is_free', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MassageDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MassageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.IntegerField()),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('name', 'duration', 'cost')},
            },
        ),
        migrations.CreateModel(
            name='MassageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage_date', models.IntegerField(choices=[(1, '2020-11-11 15:00'), (2, '2020-11-11 12:00')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('massage_delivery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='massage.massagedelivery')),
                ('massage_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='massage.massagetype')),
            ],
        ),
    ]
