# Generated by Django 3.1.2 on 2020-10-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massageservice',
            options={'ordering': ('massage_date_time',)},
        ),
        migrations.AddField(
            model_name='massageservice',
            name='massage_date_time',
            field=models.CharField(choices=[('2020-11-12 - 16:00:00', '2020-11-12 - 16:00:00'), ('2020-11-13 - 17:00:00', '2020-11-13 - 17:00:00')], default='-', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='massageservice',
            unique_together={('massage_date_time',)},
        ),
        migrations.AlterUniqueTogether(
            name='massagetype',
            unique_together={('name', 'duration')},
        ),
        migrations.RemoveField(
            model_name='massageservice',
            name='massage_date',
        ),
    ]
