# Generated by Django 3.1.2 on 2020-10-09 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0002_massageservice_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massageservice',
            options={'ordering': ('massage_date_time',)},
        ),
        migrations.AddField(
            model_name='massageservice',
            name='massage_date_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='massage.massagedatetime'),
        ),
    ]
