# Generated by Django 3.1.2 on 2020-10-08 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_admin'),
        ('massage', '0002_auto_20201006_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='massageservice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user'),
        ),
        migrations.AlterField(
            model_name='massageservice',
            name='massage_date_time',
            field=models.CharField(choices=[('2020-11-12 - 16:00:00', '2020-11-12 - 16:00:00')], max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='massageservice',
            unique_together=set(),
        ),
    ]
