# Generated by Django 3.1.2 on 2020-10-08 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_admin'),
        ('massage', '0003_auto_20201008_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massageservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.user'),
        ),
    ]
