# Generated by Django 3.1.2 on 2020-10-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0004_massagetype_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massagedatetime',
            old_name='is_free',
            new_name='is_active',
        ),
    ]
