# Generated by Django 3.1.2 on 2020-10-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0004_auto_20201008_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massageservice',
            name='user',
        ),
    ]
