# Generated by Django 3.1.2 on 2020-10-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0005_auto_20201010_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='massageservice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
