# Generated by Django 3.1.2 on 2020-10-09 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user'),
        ('massage', '0005_remove_massageservice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='massageservice',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.user'),
        ),
    ]
