# Generated by Django 3.1.2 on 2020-10-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0006_massageservice_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massagedatetime',
            options={'ordering': ('date_time',)},
        ),
    ]
