# Generated by Django 3.1.2 on 2020-10-09 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('massage', '0006_massageservice_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massageservice',
            name='massage_delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='massage.massagedelivery'),
        ),
        migrations.AlterField(
            model_name='massageservice',
            name='massage_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='massage.massagetype'),
        ),
        migrations.AlterField(
            model_name='massageservice',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
