# Generated by Django 3.1.2 on 2020-10-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0007_auto_20201010_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massagedatetime',
            options={'ordering': ('date_time', 'is_active')},
        ),
    ]
