# Generated by Django 3.1.2 on 2020-10-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0008_auto_20201010_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massagedelivery',
            name='place',
            field=models.CharField(default='Gabinet Sopot Kamienny Potok', max_length=100),
        ),
        migrations.AlterField(
            model_name='massageservice',
            name='address',
            field=models.CharField(blank=True, default='Gabinet Sopot Kamienny Potok', max_length=200, null=True),
        ),
    ]
