# Generated by Django 3.1.2 on 2020-10-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0010_auto_20201017_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='massagetype',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
