# Generated by Django 3.1.2 on 2020-10-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0011_massagetype_points'),
        ('massage', '0010_auto_20201017_0952'),
    ]

    operations = [
    ]
