# Generated by Django 3.1.2 on 2020-10-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0012_merge_20201017_1110'),
        ('massage', '0013_auto_20201017_1217'),
    ]

    operations = [
    ]
