# Generated by Django 3.1.2 on 2020-10-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0014_merge_20201017_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='massageservice',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
