# Generated by Django 3.1.2 on 2020-10-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0014_merge_20201017_1235'),
        ('massage', '0014_merge_20201017_1337'),
    ]

    operations = [
    ]
