# Generated by Django 3.1.2 on 2020-10-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0015_merge_20201017_1402'),
        ('massage', '0015_massageservice_total_cost'),
    ]

    operations = [
    ]
