# Generated by Django 3.1.2 on 2020-10-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0015_merge_20201017_1402'),
        ('massage', '0014_merge_20201017_1559'),
        ('massage', '0015_massageservice_total_cost'),
    ]

    operations = [
    ]
