# Generated by Django 3.1.2 on 2020-10-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0016_merge_20201018_0905'),
        ('massage', '0016_merge_20201017_1434'),
    ]

    operations = [
    ]
