# Generated by Django 3.1.2 on 2020-10-18 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0017_massageservice_has_taken_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massageservice',
            name='massage_date_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='massage.massagedatetime', unique=True),
        ),
    ]
