# Generated by Django 3.1.2 on 2020-10-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0018_auto_20201018_1138'),
        ('massage', '0017_merge_20201018_1041'),
    ]

    operations = [
    ]
