# Generated by Django 3.1.2 on 2020-10-04 08:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201004_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+48000000000', max_length=128, region=None),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('name', 'phone')},
        ),
    ]
