# Generated by Django 3.1.2 on 2020-10-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_masseur_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masseur',
            name='name',
            field=models.CharField(default='Man with no name', max_length=100),
        ),
    ]
