# Generated by Django 3.1.2 on 2020-10-08 18:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201004_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='slagra@tlen.pl', max_length=100, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='+48666617008', max_length=128, region=None)),
            ],
        ),
    ]
