# Generated by Django 3.1.2 on 2020-10-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0005_remove_massageservice_user'),
        ('users', '0006_user_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
