# Generated by Django 3.1.2 on 2020-10-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
