# Generated by Django 3.1.2 on 2020-10-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_is_admin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'email')},
        ),
    ]
